helm/values-dev.yaml
=> fix(deploy): fix deploy vars

src/main/kotlin/it/pagopa/wallet/client/NpgClient.kt
Add error response to applicative logs
Add error response log
expected)
=> fix: add error response log

src/main/kotlin/it/pagopa/wallet/client/NpgClient.kt, src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
* fix(npg): fix request to NPG HPP API
expected)
=> fix(npg): fix request to NPG HPP API

Dockerfile
Update base image to amazon-corretto
This modification is needed because this image support also arm64v8 architecture
Local docker build and test using project docker compose
expected)
=> fix: update docker base image to amazon-corretto

gradle/wrapper/gradle-wrapper.properties
Update gradle distribution download url
This modification is needed because the old configured distribution URL is no more working
`
#0 10.75 Exception in thread "main" java.io.IOException: Downloading from https://downloads.gradle-dn.com/distributions/gradle-8.1-bin.zip failed: timeout (10000ms)
#0 10.75 	at org.gradle.wrapper.Download.downloadInternal(Download.java:131)
#0 10.75 	at org.gradle.wrapper.Download.download(Download.java:89)
#0 10.75 	at org.gradle.wrapper.Install$1.call(Install.java:83)
#0 10.75 	at org.gradle.wrapper.Install$1.call(Install.java:63)
#0 10.75 	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
#0 10.75 	at org.gradle.wrapper.Install.createDist(Install.java:63)
#0 10.75 	at …
=> fix(build): update gradle distribution url

.devops/azure-templates/gradle-github-release.yml
Fix azure template used to perform gradle project version bump 
gradle github release task is broken and prevents release publish
expected)
=> fix(release): fixed gradle-github-release.yml template

api-spec/wallet-api.yaml, src/main/kotlin/it/pagopa/wallet/audit/LoggingEvent.kt, src/main/kotlin/it/pagopa/wallet/controllers/ServicesController.kt, src/main/kotlin/it/pagopa/wallet/documents/service/Service.kt, src/main/kotlin/it/pagopa/wallet/services/ServicesService.kt, src/test/kotlin/it/pagopa/wallet/ApplicationTest.kt, src/test/kotlin/it/pagopa/wallet/ServiceTestUtils.kt, src/test/kotlin/it/pagopa/wallet/controllers/ServicesControllerTest.kt, src/test/kotlin/it/pagopa/wallet/services/ServicesServiceTest.kt
* added `Service` domain classes
* added business logic to create new global service with auditing
* added API to controller to invoke business logic for creating new services
expected)
Depends on #36
=> [CHK-1961] feat(service): implement controller + service to create new global service

api-spec/wallet-api.yaml, src/main/kotlin/it/pagopa/wallet/audit/LoggingEvent.kt, src/main/kotlin/it/pagopa/wallet/controllers/ServicesController.kt, src/main/kotlin/it/pagopa/wallet/exception/ServiceNotFoundException.kt, src/main/kotlin/it/pagopa/wallet/services/ServicesService.kt, src/test/kotlin/it/pagopa/wallet/ServiceTestUtils.kt, src/test/kotlin/it/pagopa/wallet/controllers/ServicesControllerTest.kt, src/test/kotlin/it/pagopa/wallet/services/ServicesServiceTest.kt
* added API to change service status
This PR implements the functional requirement of allowing service status change through an API
expected)
Depends on #34
=> feat(services): add API to change service status

src/main/kotlin/it/pagopa/wallet/documents/service/Service.kt, src/test/kotlin/it/pagopa/wallet/ApplicationTest.kt
=> fix: add missing @Document annotation on Service class

src/main/kotlin/it/pagopa/wallet/domain/wallets/Wallet.kt
Fix paymentInstrumentId serialization in wallet document 
expected)
=> fix paymentInstrument serialization in document

src/main/kotlin/it/pagopa/wallet/audit/LoggingEvent.kt
Fix field name and type for logging event
expected)
=> [CHK-1961] Hot fix for dev testing

src/main/kotlin/it/pagopa/wallet/documents/wallets/Application.kt, src/main/kotlin/it/pagopa/wallet/documents/wallets/Wallet.kt, src/main/kotlin/it/pagopa/wallet/domain/wallets/Application.kt, src/main/kotlin/it/pagopa/wallet/domain/wallets/Wallet.kt, src/main/kotlin/it/pagopa/wallet/services/WalletService.kt, src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt, src/test/kotlin/it/pagopa/wallet/domain/wallets/WalletTest.kt, src/test/kotlin/it/pagopa/wallet/services/ApplicationTest.kt
Rename `WalletService` class for handling association between wallet and service to `Application` to avoid name overloading, since WalletService is also the name of the class that holds the business logic of this service
Rename also `services` field in Wallet class to `applications`
Update test
Code readability
expected)
=> [CHK-2000] feat(wallet): rename walletservice in applications

src/main/kotlin/it/pagopa/wallet/annotations/AggregateRoot.java, src/main/kotlin/it/pagopa/wallet/annotations/AggregateRootId.java, src/main/kotlin/it/pagopa/wallet/annotations/Entity.java, src/main/kotlin/it/pagopa/wallet/annotations/ValueObject.java, src/main/kotlin/it/pagopa/wallet/domain/wallets/Application.kt, src/main/kotlin/it/pagopa/wallet/domain/wallets/ContractId.kt, src/main/kotlin/it/pagopa/wallet/domain/wallets/PaymentInstrumentId.kt, src/main/kotlin/it/pagopa/wallet/domain/wallets/PaymentMethodId.kt, src/main/kotlin/it/pagopa/wallet/domain/wallets/UserId.kt, src/main/kotlin/it/pagopa/wallet/domain/wallets/Wallet.kt, src/main/kotlin/it/pagopa/wallet/domain/wallets/WalletId.kt
-  Add ddd annotations for aggregate root
The goal of this PR is to formalize the use of Aggregate Root pattern, in order to implement invariants related to wallet concept ( to do in PR with some business logic) 
expected)
=> feat(docs): Add ddd annotations for aggregate root

src/main/kotlin/it/pagopa/wallet/services/WalletService.kt, src/main/kotlin/it/pagopa/wallet/util/UniqueIdUtils.kt, src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt, src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt, src/test/kotlin/it/pagopa/wallet/util/converters/mongo/UniqueIdUtilTest.kt
For the generation of the unique orderId and contractId for NPG I thought to proceed from the timestamp in milliseconds by concatenating random way N characters between URI safe alphanumeric values.
I ruled out concurrency problems in generating the two ids in the same millisecond through a probability calculation described as follows.
Consider the length of the timestamp string in milliseconds = 13
So the random string to be generated will be 18 (maximum length of the unique id) - 13 = 5 characters
Suppose we have 2000 RPS on the service (very large number of requests) so 2 requests per millisecond.
The number of alphanumeric characters used to generate the random string is 65.
```
const val ALPHANUMERICS: String =
"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._"
``` …
=> [CHK-2057] feat  added unique id generation

api-spec/wallet-api.yaml, src/main/kotlin/it/pagopa/wallet/config/RedisConfiguration.kt, src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt, src/main/kotlin/it/pagopa/wallet/domain/details/Bin.kt, src/main/kotlin/it/pagopa/wallet/domain/details/ExpiryDate.kt, src/main/kotlin/it/pagopa/wallet/domain/details/MaskedPan.kt, src/main/kotlin/it/pagopa/wallet/exception/SessionNotFoundException.kt, src/main/kotlin/it/pagopa/wallet/services/WalletService.kt, src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt, src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt, src/test/kotlin/it/pagopa/wallet/domain/wallets/details/BinTest.kt, src/test/kotlin/it/pagopa/wallet/domain/wallets/details/CardDetailsTest.kt, src/test/kotlin/it/pagopa/wallet/domain/wallets/details/ExpiryDateTest.kt, src/test/kotlin/it/pagopa/wallet/domain/wallets/details/MaskedPanTest.kt, src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Hot fix for wallet-service
- Redis deserializer configuration
- Bin, MaskedPan and Expiry date format to be compliant with npg response
- OrderId now is a simple string (preoviously it was a UUID)
- fix junit tests
expected)
=> [CHK-2092] hotfix for wallet

helm/values-dev.yaml, helm/values-uat.yaml
* remove trailing slash from `SESSION_URL_BASEPATH` env variable
expected)
=> fix(conf): remove trailing slash from `SESSION_URL_BASEPATH` env variable

api-spec/wallet-api.yaml, src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt, src/main/kotlin/it/pagopa/wallet/repositories/WalletRepository.kt, src/main/kotlin/it/pagopa/wallet/services/WalletService.kt, src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt, src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt, src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
=> feat: CHK-2170 add find session wallet

src/main/kotlin/it/pagopa/wallet/services/WalletService.kt, src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Fix saved contract id into document after build session
expected)
=> feat: saved contract id into collection

.env.example, .env.local, README.md, docker/config/ecommerce-payment-methods/payment-method-server.json, helm/values-dev.yaml, helm/values-uat.yaml, src/main/kotlin/it/pagopa/wallet/WalletApplication.kt, src/main/kotlin/it/pagopa/wallet/config/OnboardingReturnUrlConfig.kt, src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt, src/main/kotlin/it/pagopa/wallet/domain/details/WalletDetailsType.kt, src/main/kotlin/it/pagopa/wallet/services/WalletService.kt, src/main/resources/application.properties, src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt, src/test/kotlin/it/pagopa/wallet/controllers/ServicesControllerTest.kt, src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt, src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt, src/test/resources/application.test.properties
Differentiate onboarding web-view return URI based on requested payment method type.
This PR introduces Paypal onboarding return url based on the payment method name PAYPAL.
Discrimination is made based on create wallet input payment method name
As for now, then, return urls will be:
CARDS -> `onboarding/creditcard`
PAYPAL -> `onboarding/apm`
Those modifications are needed in order to properly handle onboarding for cards onboarding/creditcard
junit tests + local test using docker local env
expected)
=> feat: differentiate redirect url for payment method apm

.env.example, .env.local
Fix env example and env local variables
Fix env example and env local variables
Local project run with env.local
expected)
=> fix: env local and env example

src/main/resources/application.properties
Added retry write into connection mongo URI
expected)
=> fix: added retryWrites=false into mongo uri

api-tests/wallet_local.collection.tests.json, src/main/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandler.kt, src/test/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandlerTest.kt
Remove error details from error responses
Remove error details from error responses
Junit tests
expected)
=> fix: remove detail error response

src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
Fix junit tests
Fix junit tests
Junit tests
expected)
=> fix: junit tests

.env.example, README.md, api-spec/wallet-api.yaml, build.gradle.kts, helm/values-dev.yaml, helm/values-uat.yaml, npg-api/npg-api.yaml, src/main/kotlin/it/pagopa/wallet/WalletApplication.kt, src/main/kotlin/it/pagopa/wallet/client/NpgClient.kt, src/main/kotlin/it/pagopa/wallet/config/OnboardingConfig.kt, src/main/kotlin/it/pagopa/wallet/config/WebClientConfig.kt, src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt, src/main/kotlin/it/pagopa/wallet/documents/wallets/details/PayPalDetails.kt, src/main/kotlin/it/pagopa/wallet/domain/details/MaskedEmail.kt, src/main/kotlin/it/pagopa/wallet/domain/details/PayPalDetails.kt, src/main/kotlin/it/pagopa/wallet/services/WalletService.kt, src/main/resources/application.properties, src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt, src/test/kotlin/it/pagopa/wallet/client/NpgClientTest.kt, src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt, src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt, src/test/resources/application.test.properties
Depends on https://github.com/pagopa/pagopa-infra/pull/1582
* return redirection url instead of form fields when creating session for APMs
This PR is needed to handle onboarding of alternative payment methods (APMs)
Unit tests
expected)
=> [CHK-2238] refactor(api): return redirection url instead of form fields when creating session for APMs

src/main/kotlin/it/pagopa/wallet/config/RedisConfiguration.kt, src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt, src/main/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandler.kt
Minor code review fixes:
1. move exception mapping to ExceptionHandler class
2. remove use of deprecated code constructing `Jackson2JsonRedisSerializer` class
1. move exception mapping to ExceptionHandler class
2. remove use of deprecated code constructing `Jackson2JsonRedisSerializer` class
Junit tests
expected)
=> Code refactoring

helm/values-dev.yaml, helm/values-uat.yaml
Fix credit card onboarding return url to lowercase
This fix has been made in order to align return urls to f.e. expected ones
expected)
=> fix(helm): fix creditcard route to lowercase

.devops/azure-templates/api-tests.yml, .devops/deploy-pipelines.yml
Fix api test executions exported files to avoid duplicate files from being exported
Fix api test executions exported files to avoid duplicate files from being exported
[CR](https://dev.azure.com/pagopaspa/pagoPA-projects/_build/results?buildId=133527&view=ms.vss-test-web.build-test-results-tab) and [deploy](https://dev.azure.com/pagopaspa/pagoPA-projects/_build/results?buildId=133528&view=results) pipeline runs
expected)
=> fix(api-test): differentiate test result exported files

api-spec/wallet-api.yaml, src/main/kotlin/it/pagopa/wallet/exception/ServiceNameNotFoundException.kt, src/main/kotlin/it/pagopa/wallet/repositories/ServiceRepository.kt, src/main/kotlin/it/pagopa/wallet/services/WalletService.kt, src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt, src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
* fix wrong search by id rather than service name when updating wallet services
* make new service list computation pure
* return 404 if a wallet service status change is requested for a nonexisting service
Mostly bug fixes :) 
Unit tests + deploy in DEV
expected)
=> fix(update-services): refactor wallet update service endpoint

src/main/kotlin/it/pagopa/wallet/documents/wallets/Application.kt, src/main/kotlin/it/pagopa/wallet/domain/services/ApplicationMetadata.kt, src/main/kotlin/it/pagopa/wallet/domain/wallets/Application.kt, src/main/kotlin/it/pagopa/wallet/domain/wallets/Wallet.kt, src/main/kotlin/it/pagopa/wallet/services/WalletService.kt, src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt, src/test/kotlin/it/pagopa/wallet/domain/wallets/WalletTest.kt, src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
- add `metadata` for `Application` domain and document
The goal of this PR is to add `metadata` property for an `Application` .
This `metadata` is required to store a set of properties that characterize an `Application Wallet`, for example for a wallet enable to pagoPA payment (application PAGOPA), if the wallet was onboarded during a payment it can be represented as follows:
```
"applications": [{
....
"metadata" : {
"onboardeWithPayment" : "true"
}
}]
```
So the idea is to model the metadata as a generic document, so in a domain as a HashMap (considering that a [Document](https://www.mongodb.com/docs/drivers/java/sync/v4.3/fundamentals/data-formats/documents/#overview) implements `Map<>`).
- unit test
expected)
=> feat: CHK-2403 add metadata for application

api-spec/wallet-api.yaml, src/main/kotlin/it/pagopa/wallet/controllers/MigrationController.kt, src/test/kotlin/it/pagopa/wallet/controllers/MigrationControllerTest.kt
- Updated swagger by adding new wallet initiazialization api for migration phase
expected)
=> [CHK-2515] Added wallet initialization api for migration

api-spec/wallet-api.yaml, src/main/kotlin/it/pagopa/wallet/controllers/MigrationController.kt, src/test/kotlin/it/pagopa/wallet/controllers/MigrationControllerTest.kt
- replace fiscalCode with userId uuid cause APIM anonymize the fiscal code and then forward request to wallet microservice
expected)
=> [CHK-2515] Removed fiscalCode from Migration API

helm/values-uat.yaml
Add missing env secret for UAT env
Missing secret make UAT pod unavailable
expected)
=> fix: add missing UAT secret

helm/values-uat.yaml
Add missing UAT env param
Add missing UAT env param
expected)
=> fix: add missing UAT env parameters

src/main/kotlin/it/pagopa/wallet/audit/LoggingEvent.kt, src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt, src/main/kotlin/it/pagopa/wallet/services/WalletService.kt, src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt, src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
* added implementation for logical deletion of wallets
This PR implements the wallet deletion API, used when a user wants to delete a payment instrument from her account.
Local unit tests + on DEV environment
expected)
=> [CHK-2561] feat(wallet): add implementation for logical deletion of wallets

helm/values-uat.yaml
Add missing green `WALLET_LOGO_MAPPING` helm values
Add missing green `WALLET_LOGO_MAPPING` helm values
expected)
=> fix(helm): add wallet logo mapping for green uat env values

.devops/deploy-pipelines.yml
=> chore(ci): converted tests steps into separated jobs

src/main/kotlin/it/pagopa/wallet/repositories/NpgSessionsTemplateWrapper.kt, src/main/kotlin/it/pagopa/wallet/services/WalletService.kt, src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
* remove url decoding of session id when creating wallet session
expected)
=> [CHK-2468] fix(npg): remove url decoding of session id when creating wallet session

api-spec/wallet-api.yaml, src/main/kotlin/it/pagopa/wallet/services/WalletService.kt, src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
- add outcome 15 to handle  `WALLET_ALREADY_ONBOARDED_FOR_USER_ERROR_CODE`
expected)
=> feat: CHK-2634 outcome 15

helm/values-uat.yaml
fix wallet logo mapping uat
expected)
=> fix(config): fix wallet logo mapping uat

src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
* fix encoding of session id when calling `getCardData` endpoint
expected)
=> fix(npg): encoding of NPG session id

helm/values-uat.yaml
Fix uat helm values config for notification url
expected)
=> fix helm config values for uat

api-spec/wallet-api.yaml, src/main/kotlin/it/pagopa/wallet/services/WalletService.kt, src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt, src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Align wallet-api specs to openapi for appIO infra
expected)
=> [CHK-2700] Align wallet-api specs to openapi for appIO infra

Dockerfile, helm/values-dev.yaml, helm/values-uat.yaml, src/main/kotlin/it/pagopa/wallet/WalletApplication.kt, src/main/kotlin/it/pagopa/wallet/reactormdc/ConfigurationContextLifterMDC.kt, src/main/kotlin/it/pagopa/wallet/reactormdc/ContextLifterMDC.kt, src/main/resources/logback-spring.xml
This PR setup Opentelemetry agent.
- add opentelemetry agent to Dockerfile
- add opentelemetry environment variables
- add reactor context lifter to include micrometer observation
Capture trace and metrics and send it to ELK collector
expected)
=> [CHK-2681] Setup OTeL agent

helm/values-uat.yaml
=> fix: add missing uat env variable

.devops/azure-templates/api-tests.yml, .devops/deploy-pipelines.yml
This PR adds a new secret env variable for migration integration testing. This new API key is reserved for CSTAR internal migration endpoint.
expected)
=> [CHK-2755] Add dedicated CSTAR api key for migration tests

src/main/kotlin/it/pagopa/wallet/config/LogoConfig.kt, src/main/kotlin/it/pagopa/wallet/controllers/MigrationController.kt, src/main/kotlin/it/pagopa/wallet/documents/wallets/details/CardDetails.kt, src/main/kotlin/it/pagopa/wallet/domain/wallets/details/CardBrand.kt, src/main/kotlin/it/pagopa/wallet/domain/wallets/details/CardDetails.kt, src/main/kotlin/it/pagopa/wallet/services/WalletService.kt, src/main/kotlin/it/pagopa/wallet/util/WalletUtils.kt, src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt, src/test/kotlin/it/pagopa/wallet/controllers/MigrationControllerTest.kt, src/test/kotlin/it/pagopa/wallet/domain/wallets/details/CardBrandTest.kt, src/test/kotlin/it/pagopa/wallet/domain/wallets/details/CardDetailsTest.kt, src/test/kotlin/it/pagopa/wallet/services/MigrationServiceTest.kt, src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt, src/test/kotlin/it/pagopa/wallet/util/WalletUtilsTest.kt
* refactor card brand handling and remap NPG's `MC` to `MASTERCARD`
This PR changes brand handling and unifies the current approach to brands in the pagoPA platform, by remapping NPG `MC` brand to `MASTERCARD`
Testing on dev
expected)
=> [CHK-2678] refactor(brand): refactor card brand handling and remap NPG's `MC` to `MASTERCARD`

api-tests/wallet_local_migration.collection.tests.json, src/main/kotlin/it/pagopa/wallet/exception/MigrationError.kt, src/main/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandler.kt, src/main/kotlin/it/pagopa/wallet/services/MigrationService.kt, src/test/kotlin/it/pagopa/wallet/services/MigrationServiceTest.kt
This PR adds check on paymentGatewayId to avoid onboarding of same card twice or more times during migration phase.
- add check on MigrationService while keeping idempotency on same card details
- add unit tests
- add postman tests
expected)
=> [CHK-2777] Add check to prevent onboarding of same payment gateway id

helm/values-dev.yaml, helm/values-uat.yaml
Add mooney as required api key for paypal
Add mooney as required api key for paypal
=> chore(conf): add mooney as required psp for paypal

api-spec/wallet-api.yaml, src/main/kotlin/it/pagopa/wallet/services/WalletService.kt, src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt, src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Edit get wallet response
Add client info to the get wallet by id and get wallets by user response body
expected)
=> [CHK-2846] feat(clients): add clients info in api spec and in wallet service response

helm/values-dev.yaml, helm/values-uat.yaml
Update NPG cancel URL to `esito` ones in order to make f.e. perform polling against NPG received outcome in POST notify callback api call
This modification is needed in order to make redirection to outcome url also for user canceled operations
expected)
=> fix(conf-NPG-urls): update cancel url to outcome ones

src/main/kotlin/it/pagopa/wallet/config/WebClientConfig.kt
Configure Netty DNS resolver to use 1 as number of dots in name resolution
This modification is a porting of the fix performed [here](https://github.com/pagopa/pagopa-ecommerce-payment-methods-service/pull/191) and applied to all clients
expected)
=> [CHK-2886] implementation tuning

helm/values-pay-wallet-dev.yaml, helm/values-pay-wallet-uat.yaml
The goal of this PR is to add affinity in helm value in order to deploy payment-wallet service only on pay-wallet dedicated nodepool (create in this PR https://github.com/pagopa/pagopa-infra/pull/2141).
expected)
=> feat(helm-values): CHK-2948 add conf for pay-wallet nodepool

.devops/pay-wallet-deploy-pipelines.yml, helm/values-pay-wallet-prod.yaml
=> feat: add pipeline for prod env

src/main/kotlin/it/pagopa/wallet/config/SerializationConfiguration.kt, src/main/resources/application.properties
Set serialization properties in configuration bean. Remove it from application properties.
This fix remove null value in json response
expected)
=> fix: serialize non null fields

helm/pay-wallet-values-dev.yaml, helm/pay-wallet-values-prod.yaml, helm/pay-wallet-values-uat.yaml
Align Italy north helm values each other for all environments
Align Italy north helm values each other for all environments
expected)
=> chore(helm-itn): align values

helm/pay-wallet-values-dev.yaml, helm/pay-wallet-values-prod.yaml, helm/pay-wallet-values-uat.yaml
Fix ITN queue names
Fix ITN queue names
expected)
=> fix(helm-itn): queue names

helm/pay-wallet-values-uat.yaml, helm/values-dev.yaml, helm/values-uat.yaml
Fix UAT itn expiration queue name
Fix UAT itn expiration queue name
expected)
=> Itn helm values alignment

.devops/code-review-pipelines.yml, .devops/deploy-pipelines.yml, helm/values-dev.yaml, helm/values-uat.yaml
Comment out WEU pipelines and helm values
The env to be used will be italy north only
=> chore(weu to itn): disable all weu pipelines and helm values

helm/pay-wallet-values-prod.yaml
Fix OTeL endpoint for PROD environment
expected)
=> fix: update OTeL endpoint for prod

.devops/pay-wallet-deploy-pipelines.yml, helm/pay-wallet-values-uat.yaml
=> feat(helm): [CHK-2971] add blue deployment

helm/pay-wallet-values-prod.yaml
=> fix: prod config for npg

helm/pay-wallet-values-prod.yaml
=> fix(ingress): remove .prod for ingress domain

src/main/kotlin/it/pagopa/wallet/services/WalletService.kt, src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Use wallet id as NPG correlation id
Using wallet id an NPG correlation id will make track all NPG api calls involved during onboarding phase easier
Junit tests
expected)
=> Chk 2979 npg correlation

api-spec/wallet-api.yaml, api-tests/wallet_local_migration.collection.tests.json, src/main/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandler.kt, src/test/kotlin/it/pagopa/wallet/controllers/MigrationControllerTest.kt
=> fix(migration): Conflict status for already onboarded wallet

src/main/kotlin/it/pagopa/wallet/controllers/TransactionWalletController.kt, src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt, src/main/kotlin/it/pagopa/wallet/warmup/ControllersWarmup.kt, src/main/kotlin/it/pagopa/wallet/warmup/annotations/WarmupFunction.kt, src/main/kotlin/it/pagopa/wallet/warmup/exceptions/WarmUpException.kt, src/main/kotlin/it/pagopa/wallet/warmup/utils/WarmupRequests.kt, src/main/kotlin/it/pagopa/wallet/warmup/utils/WarmupUtils.kt
Add warmup logic and methods for wallet controller.
All warmup requests have been made in order to go as deep as possible in processing queue avoiding writing entity to DB (using a null UUID as payment method id or wallet id in get operations and so on) so that warmup operation only perform service stimulation without making any write operation to DB
Those warmup requests are used to warm up service before accepting traffic since first request is significantly slower than the subsequent ones (bean initialization, opening connections and so on)
Local service run
expected)
=> feat: wallet controller warmup

api-spec/wallet-api.yaml, src/main/kotlin/it/pagopa/wallet/exception/MigrationError.kt, src/main/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandler.kt, src/main/kotlin/it/pagopa/wallet/services/MigrationService.kt, src/test/kotlin/it/pagopa/wallet/controllers/MigrationControllerTest.kt, src/test/kotlin/it/pagopa/wallet/services/MigrationServiceTest.kt
=> fix(migration): Return proper error code when trying to validate a deleted wallet

helm/pay-wallet-values-prod.yaml
=> fix(deploy): Reduced wallet min replicas

helm/pay-wallet-values-dev.yaml
=> chore: trigger helm major bump

src/main/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandler.kt, src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
=> fix: [CHK-3051] Map status code for optimistic lock exception

src/main/kotlin/it/pagopa/wallet/audit/LoggingEvent.kt
- use new collection for event log
The goal of this PR is to use new collectino for log event, according to this https://github.com/pagopa/pagopa-infra/pull/2380.
expected)
=> fix: update log event collection

src/main/kotlin/it/pagopa/wallet/domain/wallets/Wallet.kt, src/main/kotlin/it/pagopa/wallet/services/WalletService.kt, src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Patch wallet status api doesn't give error response if the wallet trying to patch is already in a final state
expected)
=> [CHK-3220] fix(patch-wallet): patch wallet status api 

api-tests/wallet_local_paypal.collection.tests.json
- update integration test
The goal of this PR is to update integration test running in code review pipeline in order to verify 409 for retry on `post wallets/:walletid/sessions`.
- check integration test in code review pipeline
expected)
=> fix: CHK-3294 Update api test no idempotency for post wallet/:id/sessions

helm/pay-wallet-values-prod.yaml
Scale up wallet min instances to 10 
This modification is needed in order to preventively scale up wallet service instances to 10 before the IT wallet release date, just to handle potential traffic surplus caused by the "click day" effect
expected)
=> chore: scale-up wallet min instances

src/main/kotlin/it/pagopa/wallet/exception/RestApiException.kt
- Add description to logs of RestApiException
The log that is printed when the exception is thrown is not clear, as it shows only the title. The status code and description must also be added 
Unit test
expected)
=> [MAIN-2] Add description RestApiException

.devops/pay-wallet-code-review-pipelines.yml
- updated versions for pipeline tasks which generated deprecation warnings on remote build and deploy processes
This update was needed to prevent future execution failures on code review and deploy pipelines
- Pipeline jobs executed successfully and without deprecation warnings
=> [PIDM-41] chore(azdo-pipeline-tasks): update tasks versions

.devops/azure-templates/api-tests.yml, .devops/pay-wallet-deploy-pipelines.yml
Remove wallet migration api tests 
Migration api tests are broken (misconfigured secrets in deploy pipelines) and that makes test to programmatically fail.
So tests have been completely deleted since migration api are targeted to be dismantled in the future, so there is no need to maintain those tests
Pipeline run in dev env
expected)
=> chore: remove migration api tests

helm/Chart.lock, helm/Chart.yaml, helm/pay-wallet-values-dev.yaml, helm/pay-wallet-values-prod.yaml, helm/pay-wallet-values-uat.yaml
Upgrade to helm chart 7 performing the following modifications:
- chat version update from 2.8.0 to 7.3.1
- canaryDelivery parameter update to the new template (adding canary section)
- add workload identity refs for each environment specifying the azure workload identity client id and service account name for each env
Those modification are needed in order to make payment wallet use workload identities instead of deprecated pod identity
Deploy in dev env
expected)
=> feat: upgrade to helm chart 7

helm/pay-wallet-values-dev.yaml, helm/pay-wallet-values-prod.yaml
Fix canary delivery parameters indentation
Fix canary delivery parameters indentation
deploy in dev env with canary delivery parameters on
expected)
=> chore(helm): fix canary delivery parameters indentation

helm/pay-wallet-values-uat.yaml
Update UAT OTEL collector endpoint
Update UAT OTEL collector endpoint
expected)
=> chore(OTEL): update collector endpoint

helm/pay-wallet-values-uat.yaml
Fix OTLP exporter protocol to GRPC
Fix OTLP exporter protocol to GRPC
expected)
=> fix: OTEL protocol

helm/pay-wallet-values-prod.yaml
- Changed references and protocol used for OTEL
This change permits to point to Telemetry directly via K8s Service, also changing used protocol.
expected)
=> [PIDM-275] fix: changing OTEL endpoint and protocol

.github/workflows/semver_release.yml
=> [CHK-4018] fix(pipeline): fix ci/cd pipelines

.github/workflows/semver_release.yml
=> [CHK-4018] fix(pipeline): fix gh release

helm/pay-wallet-values-uat.yaml
fix jwt issuer config
Move jwt issuer to envconfig from secret section
expected)
=> Move jwt issuer to envconfig from secret section

helm/pay-wallet-values-prod.yaml
Increase prod memory limits to 768MiB
Increase prod memory limits to 768MiB
expected)
=> chore: increase memory limits

helm/pay-wallet-values-dev.yaml, helm/pay-wallet-values-uat.yaml
=> [PIDM-826] feat(redis): migrate to standard redis

helm/pay-wallet-values-dev.yaml, helm/pay-wallet-values-prod.yaml, helm/pay-wallet-values-uat.yaml
Fix helm value to use string literal
Fix helm value to use string literal
expected)
=> chore: fix helm boolean value

src/main/kotlin/it/pagopa/wallet/controllers/TransactionWalletController.kt, src/test/kotlin/it/pagopa/wallet/controllers/TransactionWalletControllerTest.kt
=> [CHK-4503] feat(api): update POST /transactions/{transactionId}/wallets API and related tests
